apiVersion: zxwbigdata.zxw.org/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: default
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
